/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.main;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.Scanner;
/**
 *
 * @author junkaizhang
 */
public class MainJFrame extends javax.swing.JFrame {
    
    
    private MyHashTable theHT;
    private File file;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        theHT = new MyHashTable(10);
        yesButton.setVisible(false);
        noButton.setVisible(false);
        eventLabel.setVisible(false);
        
        try {
            file = new File("./employee_data.txt");
        }
        
        catch (Exception e) {
            eventLabel.setText("Something went wrong.");
        }
    }
    
    
    public MyHashTable getTheHT() {
        return theHT;
    }
    
    
    private void loadFile() {
        if (theHT.numInHashTable > 0) {
            
            for (int i = 0; i < theHT.buckets.length; i++) {
                
                for (int j = 0; j < theHT.buckets[i].size(); i++) {
                    int theEmpNum = theHT.buckets[i].get(j).getEmployeeInfo().getEmpNum();
                    
                    theHT.removeEmployee(theEmpNum);
                }
            }
        }
        
        try {
            Scanner scan = new Scanner(file);
            
            eventLabel.setText("No employees in file.");
            
            while (scan.hasNextLine()) {
                
                String[] currentLine = scan.nextLine().split("\\|");

                try {
                    String className = currentLine[0];
                    EmployeeWriter employee = (EmployeeWriter)Class.forName(className).getConstructor().newInstance();
                    employee.readFormattedEmployeeInfo(currentLine);
                    theHT.addEmployee(employee);
                    eventLabel.setText("File loaded successfully!");
                }

                catch (Exception e) {
                    eventLabel.setText("Something went wrong.");
                    break;
                }
            }

            scan.close();
        }
        
        catch (Exception e) {
            eventLabel.setText("Something went wrong.");
        }

        eventLabel.setVisible(true);
    }
    
    
    private void saveFile() {
        try {
            PrintWriter oldFile = new PrintWriter(file);
            oldFile.close();
            
            FileWriter writer = new FileWriter("./employee_data.txt", true);
            
            for (int i = 0; i < theHT.buckets.length; i++) {
                
                for (int j = 0; j < theHT.buckets[i].size(); j++) {
                
                    EmployeeWriter theEmp = theHT.buckets[i].get(j);
                    String formattedEmpInfo = theEmp.getFormattedEmpInfo();
                    writer.write(formattedEmpInfo);
                    writer.write(System.getProperty("line.separator"));
                }
            }
            
            writer.close();
            
            eventLabel.setText("Save success!");
        }

        catch (Exception e) {
            eventLabel.setText("Failed to save.");
        }
        
        finally {
            eventLabel.setVisible(true);
            loadButton.setVisible(true);
            saveButton.setVisible(true);
            displayEmpButton.setVisible(true);
            addEmpButton.setVisible(true);
            searchEmpButton.setVisible(true); 
            yesButton.setVisible(false);
            noButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        displayEmpButton = new javax.swing.JButton();
        addEmpButton = new javax.swing.JButton();
        searchEmpButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        eventLabel = new javax.swing.JLabel();
        yesButton = new javax.swing.JButton();
        noButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displayEmpButton.setText("Display Employees");
        displayEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayEmpButtonActionPerformed(evt);
            }
        });

        addEmpButton.setText("Add Employee");
        addEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmpButtonActionPerformed(evt);
            }
        });

        searchEmpButton.setText("Search Employee");
        searchEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEmpButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Load");
        loadButton.setMaximumSize(new java.awt.Dimension(132, 23));
        loadButton.setMinimumSize(new java.awt.Dimension(132, 23));
        loadButton.setPreferredSize(new java.awt.Dimension(132, 23));
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.setMaximumSize(new java.awt.Dimension(132, 23));
        saveButton.setMinimumSize(new java.awt.Dimension(132, 23));
        saveButton.setPreferredSize(new java.awt.Dimension(132, 23));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        eventLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eventLabel.setText("Event Label");
        eventLabel.setMaximumSize(new java.awt.Dimension(200, 17));
        eventLabel.setMinimumSize(new java.awt.Dimension(65, 17));
        eventLabel.setPreferredSize(new java.awt.Dimension(65, 17));

        yesButton.setText("Yes");
        yesButton.setMaximumSize(new java.awt.Dimension(80, 23));
        yesButton.setMinimumSize(new java.awt.Dimension(80, 23));
        yesButton.setPreferredSize(new java.awt.Dimension(80, 23));
        yesButton.setSize(new java.awt.Dimension(80, 23));
        yesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesButtonActionPerformed(evt);
            }
        });

        noButton.setText("No");
        noButton.setMaximumSize(new java.awt.Dimension(80, 23));
        noButton.setMinimumSize(new java.awt.Dimension(80, 23));
        noButton.setPreferredSize(new java.awt.Dimension(80, 23));
        noButton.setSize(new java.awt.Dimension(80, 23));
        noButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(eventLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(displayEmpButton)
                .addGap(18, 18, 18)
                .addComponent(addEmpButton)
                .addGap(18, 18, 18)
                .addComponent(searchEmpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(eventLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayEmpButtonActionPerformed
        // TODO add your handling code here:
        
        SeparateJFrame theSeparateJFrame = new SeparateJFrame();
        theSeparateJFrame.setVisible(true);
        theSeparateJFrame.setMainHT(theHT);
        theSeparateJFrame.displayTable();
        eventLabel.setVisible(false);
    }//GEN-LAST:event_displayEmpButtonActionPerformed

    private void addEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmpButtonActionPerformed
        // TODO add your handling code here:
        AddNewEmployeeJFrame theANEJFrame = new AddNewEmployeeJFrame();
        theANEJFrame.setVisible(true);
        theANEJFrame.setMainHT(theHT);
        eventLabel.setVisible(false);

    }//GEN-LAST:event_addEmpButtonActionPerformed

    private void searchEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEmpButtonActionPerformed
        // TODO add your handling code here:
        EmployeeSearchJFrame theESJFrame = new EmployeeSearchJFrame();
        theESJFrame.setVisible(true);
        theESJFrame.setMainHT(theHT);
        eventLabel.setVisible(false);
    }//GEN-LAST:event_searchEmpButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
        eventLabel.setVisible(false);
        
        loadFile();
    }//GEN-LAST:event_loadButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        eventLabel.setText("Save? (previous save will be deleted)");
        eventLabel.setVisible(true);
        yesButton.setVisible(true);
        noButton.setVisible(true);
        loadButton.setVisible(false);
        saveButton.setVisible(false);
        displayEmpButton.setVisible(false);
        addEmpButton.setVisible(false);
        searchEmpButton.setVisible(false);    
    }//GEN-LAST:event_saveButtonActionPerformed

    private void yesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesButtonActionPerformed
        // TODO add your handling code here:
        eventLabel.setVisible(false);
        
        saveFile();
    }//GEN-LAST:event_yesButtonActionPerformed

    private void noButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noButtonActionPerformed
        // TODO add your handling code here:
        loadButton.setVisible(true);
        saveButton.setVisible(true);
        displayEmpButton.setVisible(true);
        addEmpButton.setVisible(true);
        searchEmpButton.setVisible(true);
        yesButton.setVisible(false);
        noButton.setVisible(false);
        eventLabel.setVisible(false);
    }//GEN-LAST:event_noButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmpButton;
    private javax.swing.JButton displayEmpButton;
    private javax.swing.JLabel eventLabel;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton noButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton searchEmpButton;
    private javax.swing.JButton yesButton;
    // End of variables declaration//GEN-END:variables
}
